import type { Metadata } from 'next'
import SideBar from '../../components/side-bar'
// These styles apply to every route in the application
import './globals.css'
import { getProjects } from '../../lib/actions'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const projects = await getProjects();

  return (
    <html lang="en">
      <body>
        <main className="h-screen my-8 flex">
          <SideBar projects={projects}>
          </SideBar>
          {children}
        </main>
      </body>
    </html>
  )
}
